include("shadow/reflect.jl")
include("shadow/purity.jl")
include("shadow/z_r.jl")
include("shadow/reversal.jl")
include("shadow/z_t.jl")
include("hamming/reflect.jl")
include("hamming/purity.jl")
include("hamming/z_r.jl")
include("hamming/reversal.jl")
include("hamming/z_t.jl")

