[deps]
qiskit-aer = ""
tqdm = ""
pylatexenc = ""
matplotlib = ""
seaborn = ""
numpy = ""
qiskit = ""

[pip.deps]
quarkstudio = ""

    [pip.deps.qmeas]
    editable = true
    version = "@file:///home/mintusr/sync/theory/physics/contemporary_physics/quant_comp_note/03_tools_practice/qmeas"
