[deps]
qiskit-aer = ""
qiskit-ibm-runtime = ""
tqdm = ""
pylatexenc = ""
pip = ""
matplotlib = ""
seaborn = ""
numpy = ""
qiskit-algorithms = ""
qiskit = ""

[pip.deps]
quarkstudio = ""
quarkcircuit = ""
